server:
  port: 8070

logging:
  config: classpath:log4j2.yml
mybatis:
  config-location: classpath:mybatis.cfg.xml     # mybatis配置文件所在路径
  mapper-locations: classpath:com/initpassion/cache/dao/**/*Mapper.xml     # 所有的mapper映射文件

#开发配置
spring:
  datasource:
    url: jdbc:mysql://47.93.254.25:3306/initpassion?useUnicode=yes&characterEncoding=utf8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    dbcp2:  # 进行数据库连接池的配置
        min-idle: 5         # 数据库连接池的最小维持连接数
        initial-size: 5      # 初始化提供的连接数
        max-total: 5          # 最大的连接数
        max-wait-millis: 200  # 等待连接获取的最大超时时间

app:
  id: Cacha.Test

apollo:
  meta: http://47.93.254.25:8080

Deureka:
  instance:
    homePageUrl: http://47.93.254.25:8080


